# Generated by Django 5.2.8 on 2025-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.FloatField()),
                ('education', models.FloatField()),
                ('employment_status', models.FloatField()),
                ('employment_sector', models.FloatField()),
                ('income_bracket', models.FloatField()),
                ('marital_status', models.FloatField()),
                ('household_size', models.FloatField()),
                ('has_children', models.FloatField()),
                ('urbanicity', models.FloatField()),
                ('region', models.FloatField()),
                ('voted_last', models.FloatField()),
                ('party_id_strength', models.FloatField()),
                ('union_member', models.FloatField()),
                ('public_sector', models.FloatField()),
                ('home_owner', models.FloatField()),
                ('small_biz_owner', models.FloatField()),
                ('owns_car', models.FloatField()),
                ('will_turnout', models.FloatField()),
                ('undecided', models.FloatField()),
                ('preference_strength', models.FloatField()),
                ('tv_news_hours', models.FloatField()),
                ('social_media_hours', models.FloatField()),
                ('trust_media', models.FloatField()),
                ('civic_participation', models.FloatField()),
                ('job_tenure_years', models.FloatField()),
                ('predicted_vote', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
