# Generated by Django 5.2.8 on 2025-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='age_group',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='votante',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='votante',
            name='media_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='votante',
            name='political_engagement',
            field=models.FloatField(default=0),
        ),
    ]
